/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-07 15:58:32 UTC)
 * on 2013-05-09 at 11:24:22 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint;

/**
 * Service definition for Procedureendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ProcedureendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Procedureendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://reflectionappbackend.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "procedureendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Procedureendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Procedureendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getProcedure".
   *
   * This request holds the parameters needed by the the procedureendpoint server.  After setting any
   * optional parameters, call the {@link GetProcedure#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetProcedure getProcedure(java.lang.Long id) throws java.io.IOException {
    GetProcedure result = new GetProcedure(id);
    initialize(result);
    return result;
  }

  public class GetProcedure extends ProcedureendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure> {

    private static final String REST_PATH = "procedure/{id}";

    /**
     * Create a request for the method "getProcedure".
     *
     * This request holds the parameters needed by the the procedureendpoint server.  After setting
     * any optional parameters, call the {@link GetProcedure#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetProcedure#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetProcedure(java.lang.Long id) {
      super(Procedureendpoint.this, "GET", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProcedure setAlt(java.lang.String alt) {
      return (GetProcedure) super.setAlt(alt);
    }

    @Override
    public GetProcedure setFields(java.lang.String fields) {
      return (GetProcedure) super.setFields(fields);
    }

    @Override
    public GetProcedure setKey(java.lang.String key) {
      return (GetProcedure) super.setKey(key);
    }

    @Override
    public GetProcedure setOauthToken(java.lang.String oauthToken) {
      return (GetProcedure) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProcedure setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetProcedure) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProcedure setQuotaUser(java.lang.String quotaUser) {
      return (GetProcedure) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProcedure setUserIp(java.lang.String userIp) {
      return (GetProcedure) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetProcedure setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetProcedure set(String parameterName, Object value) {
      return (GetProcedure) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertProcedure".
   *
   * This request holds the parameters needed by the the procedureendpoint server.  After setting any
   * optional parameters, call the {@link InsertProcedure#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure}
   * @return the request
   */
  public InsertProcedure insertProcedure(com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure content) throws java.io.IOException {
    InsertProcedure result = new InsertProcedure(content);
    initialize(result);
    return result;
  }

  public class InsertProcedure extends ProcedureendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure> {

    private static final String REST_PATH = "procedure";

    /**
     * Create a request for the method "insertProcedure".
     *
     * This request holds the parameters needed by the the procedureendpoint server.  After setting
     * any optional parameters, call the {@link InsertProcedure#execute()} method to invoke the remote
     * operation. <p> {@link InsertProcedure#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure}
     * @since 1.13
     */
    protected InsertProcedure(com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure content) {
      super(Procedureendpoint.this, "POST", REST_PATH, content, com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure.class);
    }

    @Override
    public InsertProcedure setAlt(java.lang.String alt) {
      return (InsertProcedure) super.setAlt(alt);
    }

    @Override
    public InsertProcedure setFields(java.lang.String fields) {
      return (InsertProcedure) super.setFields(fields);
    }

    @Override
    public InsertProcedure setKey(java.lang.String key) {
      return (InsertProcedure) super.setKey(key);
    }

    @Override
    public InsertProcedure setOauthToken(java.lang.String oauthToken) {
      return (InsertProcedure) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertProcedure setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertProcedure) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertProcedure setQuotaUser(java.lang.String quotaUser) {
      return (InsertProcedure) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertProcedure setUserIp(java.lang.String userIp) {
      return (InsertProcedure) super.setUserIp(userIp);
    }

    @Override
    public InsertProcedure set(String parameterName, Object value) {
      return (InsertProcedure) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listProcedure".
   *
   * This request holds the parameters needed by the the procedureendpoint server.  After setting any
   * optional parameters, call the {@link ListProcedure#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListProcedure listProcedure() throws java.io.IOException {
    ListProcedure result = new ListProcedure();
    initialize(result);
    return result;
  }

  public class ListProcedure extends ProcedureendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.CollectionResponseProcedure> {

    private static final String REST_PATH = "procedure";

    /**
     * Create a request for the method "listProcedure".
     *
     * This request holds the parameters needed by the the procedureendpoint server.  After setting
     * any optional parameters, call the {@link ListProcedure#execute()} method to invoke the remote
     * operation. <p> {@link ListProcedure#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListProcedure() {
      super(Procedureendpoint.this, "GET", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.CollectionResponseProcedure.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListProcedure setAlt(java.lang.String alt) {
      return (ListProcedure) super.setAlt(alt);
    }

    @Override
    public ListProcedure setFields(java.lang.String fields) {
      return (ListProcedure) super.setFields(fields);
    }

    @Override
    public ListProcedure setKey(java.lang.String key) {
      return (ListProcedure) super.setKey(key);
    }

    @Override
    public ListProcedure setOauthToken(java.lang.String oauthToken) {
      return (ListProcedure) super.setOauthToken(oauthToken);
    }

    @Override
    public ListProcedure setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListProcedure) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListProcedure setQuotaUser(java.lang.String quotaUser) {
      return (ListProcedure) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListProcedure setUserIp(java.lang.String userIp) {
      return (ListProcedure) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListProcedure setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListProcedure setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListProcedure set(String parameterName, Object value) {
      return (ListProcedure) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeProcedure".
   *
   * This request holds the parameters needed by the the procedureendpoint server.  After setting any
   * optional parameters, call the {@link RemoveProcedure#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveProcedure removeProcedure(java.lang.Long id) throws java.io.IOException {
    RemoveProcedure result = new RemoveProcedure(id);
    initialize(result);
    return result;
  }

  public class RemoveProcedure extends ProcedureendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure> {

    private static final String REST_PATH = "procedure/{id}";

    /**
     * Create a request for the method "removeProcedure".
     *
     * This request holds the parameters needed by the the procedureendpoint server.  After setting
     * any optional parameters, call the {@link RemoveProcedure#execute()} method to invoke the remote
     * operation. <p> {@link RemoveProcedure#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveProcedure(java.lang.Long id) {
      super(Procedureendpoint.this, "DELETE", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveProcedure setAlt(java.lang.String alt) {
      return (RemoveProcedure) super.setAlt(alt);
    }

    @Override
    public RemoveProcedure setFields(java.lang.String fields) {
      return (RemoveProcedure) super.setFields(fields);
    }

    @Override
    public RemoveProcedure setKey(java.lang.String key) {
      return (RemoveProcedure) super.setKey(key);
    }

    @Override
    public RemoveProcedure setOauthToken(java.lang.String oauthToken) {
      return (RemoveProcedure) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveProcedure setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveProcedure) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveProcedure setQuotaUser(java.lang.String quotaUser) {
      return (RemoveProcedure) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveProcedure setUserIp(java.lang.String userIp) {
      return (RemoveProcedure) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveProcedure setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveProcedure set(String parameterName, Object value) {
      return (RemoveProcedure) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateProcedure".
   *
   * This request holds the parameters needed by the the procedureendpoint server.  After setting any
   * optional parameters, call the {@link UpdateProcedure#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure}
   * @return the request
   */
  public UpdateProcedure updateProcedure(com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure content) throws java.io.IOException {
    UpdateProcedure result = new UpdateProcedure(content);
    initialize(result);
    return result;
  }

  public class UpdateProcedure extends ProcedureendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure> {

    private static final String REST_PATH = "procedure";

    /**
     * Create a request for the method "updateProcedure".
     *
     * This request holds the parameters needed by the the procedureendpoint server.  After setting
     * any optional parameters, call the {@link UpdateProcedure#execute()} method to invoke the remote
     * operation. <p> {@link UpdateProcedure#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure}
     * @since 1.13
     */
    protected UpdateProcedure(com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure content) {
      super(Procedureendpoint.this, "PUT", REST_PATH, content, com.google.api.services.no.ntnu.emergencyreflect.procedureendpoint.model.Procedure.class);
    }

    @Override
    public UpdateProcedure setAlt(java.lang.String alt) {
      return (UpdateProcedure) super.setAlt(alt);
    }

    @Override
    public UpdateProcedure setFields(java.lang.String fields) {
      return (UpdateProcedure) super.setFields(fields);
    }

    @Override
    public UpdateProcedure setKey(java.lang.String key) {
      return (UpdateProcedure) super.setKey(key);
    }

    @Override
    public UpdateProcedure setOauthToken(java.lang.String oauthToken) {
      return (UpdateProcedure) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateProcedure setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateProcedure) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateProcedure setQuotaUser(java.lang.String quotaUser) {
      return (UpdateProcedure) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateProcedure setUserIp(java.lang.String userIp) {
      return (UpdateProcedure) super.setUserIp(userIp);
    }

    @Override
    public UpdateProcedure set(String parameterName, Object value) {
      return (UpdateProcedure) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Procedureendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Procedureendpoint}. */
    @Override
    public Procedureendpoint build() {
      return new Procedureendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ProcedureendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setProcedureendpointRequestInitializer(
        ProcedureendpointRequestInitializer procedureendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(procedureendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
