/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-07 15:58:32 UTC)
 * on 2013-05-09 at 11:24:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.no.ntnu.emergencyreflect.stependpoint;

/**
 * Service definition for Stependpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StependpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Stependpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://reflectionappbackend.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "stependpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Stependpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Stependpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStep".
   *
   * This request holds the parameters needed by the the stependpoint server.  After setting any
   * optional parameters, call the {@link GetStep#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetStep getStep(java.lang.Long id) throws java.io.IOException {
    GetStep result = new GetStep(id);
    initialize(result);
    return result;
  }

  public class GetStep extends StependpointRequest<com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step> {

    private static final String REST_PATH = "step/{id}";

    /**
     * Create a request for the method "getStep".
     *
     * This request holds the parameters needed by the the stependpoint server.  After setting any
     * optional parameters, call the {@link GetStep#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetStep#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStep(java.lang.Long id) {
      super(Stependpoint.this, "GET", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStep setAlt(java.lang.String alt) {
      return (GetStep) super.setAlt(alt);
    }

    @Override
    public GetStep setFields(java.lang.String fields) {
      return (GetStep) super.setFields(fields);
    }

    @Override
    public GetStep setKey(java.lang.String key) {
      return (GetStep) super.setKey(key);
    }

    @Override
    public GetStep setOauthToken(java.lang.String oauthToken) {
      return (GetStep) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStep setQuotaUser(java.lang.String quotaUser) {
      return (GetStep) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStep setUserIp(java.lang.String userIp) {
      return (GetStep) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetStep setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStep set(String parameterName, Object value) {
      return (GetStep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStep".
   *
   * This request holds the parameters needed by the the stependpoint server.  After setting any
   * optional parameters, call the {@link InsertStep#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step}
   * @return the request
   */
  public InsertStep insertStep(com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step content) throws java.io.IOException {
    InsertStep result = new InsertStep(content);
    initialize(result);
    return result;
  }

  public class InsertStep extends StependpointRequest<com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step> {

    private static final String REST_PATH = "step";

    /**
     * Create a request for the method "insertStep".
     *
     * This request holds the parameters needed by the the stependpoint server.  After setting any
     * optional parameters, call the {@link InsertStep#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertStep#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step}
     * @since 1.13
     */
    protected InsertStep(com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step content) {
      super(Stependpoint.this, "POST", REST_PATH, content, com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step.class);
    }

    @Override
    public InsertStep setAlt(java.lang.String alt) {
      return (InsertStep) super.setAlt(alt);
    }

    @Override
    public InsertStep setFields(java.lang.String fields) {
      return (InsertStep) super.setFields(fields);
    }

    @Override
    public InsertStep setKey(java.lang.String key) {
      return (InsertStep) super.setKey(key);
    }

    @Override
    public InsertStep setOauthToken(java.lang.String oauthToken) {
      return (InsertStep) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStep setQuotaUser(java.lang.String quotaUser) {
      return (InsertStep) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStep setUserIp(java.lang.String userIp) {
      return (InsertStep) super.setUserIp(userIp);
    }

    @Override
    public InsertStep set(String parameterName, Object value) {
      return (InsertStep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStep".
   *
   * This request holds the parameters needed by the the stependpoint server.  After setting any
   * optional parameters, call the {@link ListStep#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListStep listStep() throws java.io.IOException {
    ListStep result = new ListStep();
    initialize(result);
    return result;
  }

  public class ListStep extends StependpointRequest<com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.CollectionResponseStep> {

    private static final String REST_PATH = "step";

    /**
     * Create a request for the method "listStep".
     *
     * This request holds the parameters needed by the the stependpoint server.  After setting any
     * optional parameters, call the {@link ListStep#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListStep#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStep() {
      super(Stependpoint.this, "GET", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.CollectionResponseStep.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStep setAlt(java.lang.String alt) {
      return (ListStep) super.setAlt(alt);
    }

    @Override
    public ListStep setFields(java.lang.String fields) {
      return (ListStep) super.setFields(fields);
    }

    @Override
    public ListStep setKey(java.lang.String key) {
      return (ListStep) super.setKey(key);
    }

    @Override
    public ListStep setOauthToken(java.lang.String oauthToken) {
      return (ListStep) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStep setQuotaUser(java.lang.String quotaUser) {
      return (ListStep) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStep setUserIp(java.lang.String userIp) {
      return (ListStep) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStep setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStep setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStep set(String parameterName, Object value) {
      return (ListStep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStep".
   *
   * This request holds the parameters needed by the the stependpoint server.  After setting any
   * optional parameters, call the {@link RemoveStep#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStep removeStep(java.lang.Long id) throws java.io.IOException {
    RemoveStep result = new RemoveStep(id);
    initialize(result);
    return result;
  }

  public class RemoveStep extends StependpointRequest<com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step> {

    private static final String REST_PATH = "step/{id}";

    /**
     * Create a request for the method "removeStep".
     *
     * This request holds the parameters needed by the the stependpoint server.  After setting any
     * optional parameters, call the {@link RemoveStep#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveStep#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStep(java.lang.Long id) {
      super(Stependpoint.this, "DELETE", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStep setAlt(java.lang.String alt) {
      return (RemoveStep) super.setAlt(alt);
    }

    @Override
    public RemoveStep setFields(java.lang.String fields) {
      return (RemoveStep) super.setFields(fields);
    }

    @Override
    public RemoveStep setKey(java.lang.String key) {
      return (RemoveStep) super.setKey(key);
    }

    @Override
    public RemoveStep setOauthToken(java.lang.String oauthToken) {
      return (RemoveStep) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStep setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStep) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStep setUserIp(java.lang.String userIp) {
      return (RemoveStep) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveStep setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStep set(String parameterName, Object value) {
      return (RemoveStep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStep".
   *
   * This request holds the parameters needed by the the stependpoint server.  After setting any
   * optional parameters, call the {@link UpdateStep#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step}
   * @return the request
   */
  public UpdateStep updateStep(com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step content) throws java.io.IOException {
    UpdateStep result = new UpdateStep(content);
    initialize(result);
    return result;
  }

  public class UpdateStep extends StependpointRequest<com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step> {

    private static final String REST_PATH = "step";

    /**
     * Create a request for the method "updateStep".
     *
     * This request holds the parameters needed by the the stependpoint server.  After setting any
     * optional parameters, call the {@link UpdateStep#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateStep#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step}
     * @since 1.13
     */
    protected UpdateStep(com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step content) {
      super(Stependpoint.this, "PUT", REST_PATH, content, com.google.api.services.no.ntnu.emergencyreflect.stependpoint.model.Step.class);
    }

    @Override
    public UpdateStep setAlt(java.lang.String alt) {
      return (UpdateStep) super.setAlt(alt);
    }

    @Override
    public UpdateStep setFields(java.lang.String fields) {
      return (UpdateStep) super.setFields(fields);
    }

    @Override
    public UpdateStep setKey(java.lang.String key) {
      return (UpdateStep) super.setKey(key);
    }

    @Override
    public UpdateStep setOauthToken(java.lang.String oauthToken) {
      return (UpdateStep) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStep setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStep) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStep setUserIp(java.lang.String userIp) {
      return (UpdateStep) super.setUserIp(userIp);
    }

    @Override
    public UpdateStep set(String parameterName, Object value) {
      return (UpdateStep) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Stependpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Stependpoint}. */
    @Override
    public Stependpoint build() {
      return new Stependpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StependpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStependpointRequestInitializer(
        StependpointRequestInitializer stependpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(stependpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
