/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-07 15:58:32 UTC)
 * on 2013-05-09 at 11:24:11 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.no.ntnu.emergencyreflect.resultendpoint;

/**
 * Service definition for Resultendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ResultendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Resultendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://reflectionappbackend.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "resultendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Resultendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Resultendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getResult".
   *
   * This request holds the parameters needed by the the resultendpoint server.  After setting any
   * optional parameters, call the {@link GetResult#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetResult getResult(java.lang.Long id) throws java.io.IOException {
    GetResult result = new GetResult(id);
    initialize(result);
    return result;
  }

  public class GetResult extends ResultendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result> {

    private static final String REST_PATH = "result/{id}";

    /**
     * Create a request for the method "getResult".
     *
     * This request holds the parameters needed by the the resultendpoint server.  After setting any
     * optional parameters, call the {@link GetResult#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetResult#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetResult(java.lang.Long id) {
      super(Resultendpoint.this, "GET", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetResult setAlt(java.lang.String alt) {
      return (GetResult) super.setAlt(alt);
    }

    @Override
    public GetResult setFields(java.lang.String fields) {
      return (GetResult) super.setFields(fields);
    }

    @Override
    public GetResult setKey(java.lang.String key) {
      return (GetResult) super.setKey(key);
    }

    @Override
    public GetResult setOauthToken(java.lang.String oauthToken) {
      return (GetResult) super.setOauthToken(oauthToken);
    }

    @Override
    public GetResult setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetResult) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetResult setQuotaUser(java.lang.String quotaUser) {
      return (GetResult) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetResult setUserIp(java.lang.String userIp) {
      return (GetResult) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetResult setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetResult set(String parameterName, Object value) {
      return (GetResult) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertResult".
   *
   * This request holds the parameters needed by the the resultendpoint server.  After setting any
   * optional parameters, call the {@link InsertResult#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result}
   * @return the request
   */
  public InsertResult insertResult(com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result content) throws java.io.IOException {
    InsertResult result = new InsertResult(content);
    initialize(result);
    return result;
  }

  public class InsertResult extends ResultendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result> {

    private static final String REST_PATH = "result";

    /**
     * Create a request for the method "insertResult".
     *
     * This request holds the parameters needed by the the resultendpoint server.  After setting any
     * optional parameters, call the {@link InsertResult#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertResult#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result}
     * @since 1.13
     */
    protected InsertResult(com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result content) {
      super(Resultendpoint.this, "POST", REST_PATH, content, com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result.class);
    }

    @Override
    public InsertResult setAlt(java.lang.String alt) {
      return (InsertResult) super.setAlt(alt);
    }

    @Override
    public InsertResult setFields(java.lang.String fields) {
      return (InsertResult) super.setFields(fields);
    }

    @Override
    public InsertResult setKey(java.lang.String key) {
      return (InsertResult) super.setKey(key);
    }

    @Override
    public InsertResult setOauthToken(java.lang.String oauthToken) {
      return (InsertResult) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertResult setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertResult) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertResult setQuotaUser(java.lang.String quotaUser) {
      return (InsertResult) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertResult setUserIp(java.lang.String userIp) {
      return (InsertResult) super.setUserIp(userIp);
    }

    @Override
    public InsertResult set(String parameterName, Object value) {
      return (InsertResult) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listResult".
   *
   * This request holds the parameters needed by the the resultendpoint server.  After setting any
   * optional parameters, call the {@link ListResult#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListResult listResult() throws java.io.IOException {
    ListResult result = new ListResult();
    initialize(result);
    return result;
  }

  public class ListResult extends ResultendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.CollectionResponseResult> {

    private static final String REST_PATH = "result";

    /**
     * Create a request for the method "listResult".
     *
     * This request holds the parameters needed by the the resultendpoint server.  After setting any
     * optional parameters, call the {@link ListResult#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListResult#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListResult() {
      super(Resultendpoint.this, "GET", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.CollectionResponseResult.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListResult setAlt(java.lang.String alt) {
      return (ListResult) super.setAlt(alt);
    }

    @Override
    public ListResult setFields(java.lang.String fields) {
      return (ListResult) super.setFields(fields);
    }

    @Override
    public ListResult setKey(java.lang.String key) {
      return (ListResult) super.setKey(key);
    }

    @Override
    public ListResult setOauthToken(java.lang.String oauthToken) {
      return (ListResult) super.setOauthToken(oauthToken);
    }

    @Override
    public ListResult setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListResult) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListResult setQuotaUser(java.lang.String quotaUser) {
      return (ListResult) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListResult setUserIp(java.lang.String userIp) {
      return (ListResult) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListResult setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListResult setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListResult set(String parameterName, Object value) {
      return (ListResult) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeResult".
   *
   * This request holds the parameters needed by the the resultendpoint server.  After setting any
   * optional parameters, call the {@link RemoveResult#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveResult removeResult(java.lang.Long id) throws java.io.IOException {
    RemoveResult result = new RemoveResult(id);
    initialize(result);
    return result;
  }

  public class RemoveResult extends ResultendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result> {

    private static final String REST_PATH = "result/{id}";

    /**
     * Create a request for the method "removeResult".
     *
     * This request holds the parameters needed by the the resultendpoint server.  After setting any
     * optional parameters, call the {@link RemoveResult#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveResult#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveResult(java.lang.Long id) {
      super(Resultendpoint.this, "DELETE", REST_PATH, null, com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveResult setAlt(java.lang.String alt) {
      return (RemoveResult) super.setAlt(alt);
    }

    @Override
    public RemoveResult setFields(java.lang.String fields) {
      return (RemoveResult) super.setFields(fields);
    }

    @Override
    public RemoveResult setKey(java.lang.String key) {
      return (RemoveResult) super.setKey(key);
    }

    @Override
    public RemoveResult setOauthToken(java.lang.String oauthToken) {
      return (RemoveResult) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveResult setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveResult) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveResult setQuotaUser(java.lang.String quotaUser) {
      return (RemoveResult) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveResult setUserIp(java.lang.String userIp) {
      return (RemoveResult) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveResult setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveResult set(String parameterName, Object value) {
      return (RemoveResult) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateResult".
   *
   * This request holds the parameters needed by the the resultendpoint server.  After setting any
   * optional parameters, call the {@link UpdateResult#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result}
   * @return the request
   */
  public UpdateResult updateResult(com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result content) throws java.io.IOException {
    UpdateResult result = new UpdateResult(content);
    initialize(result);
    return result;
  }

  public class UpdateResult extends ResultendpointRequest<com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result> {

    private static final String REST_PATH = "result";

    /**
     * Create a request for the method "updateResult".
     *
     * This request holds the parameters needed by the the resultendpoint server.  After setting any
     * optional parameters, call the {@link UpdateResult#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateResult#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result}
     * @since 1.13
     */
    protected UpdateResult(com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result content) {
      super(Resultendpoint.this, "PUT", REST_PATH, content, com.google.api.services.no.ntnu.emergencyreflect.resultendpoint.model.Result.class);
    }

    @Override
    public UpdateResult setAlt(java.lang.String alt) {
      return (UpdateResult) super.setAlt(alt);
    }

    @Override
    public UpdateResult setFields(java.lang.String fields) {
      return (UpdateResult) super.setFields(fields);
    }

    @Override
    public UpdateResult setKey(java.lang.String key) {
      return (UpdateResult) super.setKey(key);
    }

    @Override
    public UpdateResult setOauthToken(java.lang.String oauthToken) {
      return (UpdateResult) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateResult setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateResult) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateResult setQuotaUser(java.lang.String quotaUser) {
      return (UpdateResult) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateResult setUserIp(java.lang.String userIp) {
      return (UpdateResult) super.setUserIp(userIp);
    }

    @Override
    public UpdateResult set(String parameterName, Object value) {
      return (UpdateResult) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Resultendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Resultendpoint}. */
    @Override
    public Resultendpoint build() {
      return new Resultendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ResultendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setResultendpointRequestInitializer(
        ResultendpointRequestInitializer resultendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(resultendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
